### ISSUE TITLE
Is is possible to change the FluentD runAsUser?

### ISSUE THREAD

**Issue by sathishpuranik** [kube-logging/helm-charts#10]
Hi Team,

I need to change the runAsUser account for fluentd id to 2154 instead of default fluent user 100. How do you I do that? I dont see this enabled inside the helm chart. Can you please confirm on that?

**Comment by pepov** [comment]
It can be configured through the logging operator's `logging` resource:
```
spec:
  fluentd:
    security:
      securityContext:
        runAsUser: 2154
```

let me know if that worked, please create an issue in the [logging-operator](https://github.com/kube-logging/logging-operator) repo if not.
